version: '3.5'

# 2021-06-110
# PRODUCCION- Se van a arrancar los servicios:
# nginx mariadb php-fpm adminer workspace

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local
# 2021-04-14 Añadido por sugerencia de https://gist.github.com/ijaureguialzo/bf10504c742b44122ba62bfafe772c1c
  mariadb_data:
    driver: local
  adminer:
    driver: local

services:

  ### Workspace Utilities ##################################
    workspace:
      build:
        context: ./workspace
        args:
          - CHANGE_SOURCE=false
          - SHELL_OH_MY_ZSH=false
          - SHELL_OH_MY_ZSH_AUTOSUGESTIONS=false
          - SHELL_OH_MY_ZSH_ALIASES=false
          - UBUNTU_SOURCE=aliyun
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=7.4
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_SUBVERSION=false
          - INSTALL_BZ2=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=
          - INSTALL_SSH2=true
          - INSTALL_SOAP=false
          - INSTALL_XSL=false
          - INSTALL_LDAP=false
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_GEARMAN=false
          - INSTALL_PHPREDIS=true
          - INSTALL_MSSQL=false
          - NVM_NODEJS_ORG_MIRROR=
          - INSTALL_NODE=true
          - NPM_REGISTRY=
          - NPM_FETCH_RETRIES=2
          - NPM_FETCH_RETRY_FACTOR=10
          - NPM_FETCH_RETRY_MINTIMEOUT=10000
          - NPM_FETCH_RETRY_MAXTIMEOUT=60000
          - INSTALL_PNPM=false
          - INSTALL_YARN=true
          - INSTALL_NPM_GULP=true
          - INSTALL_NPM_BOWER=false
          - INSTALL_NPM_VUE_CLI=true
          - INSTALL_NPM_ANGULAR_CLI=false
          - INSTALL_DRUSH=false
          - INSTALL_WP_CLI=false
          - INSTALL_DRUPAL_CONSOLE=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_V8JS=false
          - COMPOSER_GLOBAL_INSTALL=true
          - COMPOSER_VERSION=2
          - COMPOSER_AUTH=false
          - COMPOSER_REPO_PACKAGIST=
          - INSTALL_WORKSPACE_SSH=true
          - INSTALL_LARAVEL_ENVOY=false
          - INSTALL_LARAVEL_INSTALLER=true
          - INSTALL_DEPLOYER=false
          - INSTALL_PRESTISSIMO=false
          - INSTALL_LINUXBREW=false
          - INSTALL_MC=false
          - INSTALL_SYMFONY=false
          - INSTALL_PYTHON=false
          - INSTALL_PYTHON3=false
          - INSTALL_IMAGE_OPTIMIZERS=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_TERRAFORM=false
          - INSTALL_DUSK_DEPS=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_LIBPNG=false
          - INSTALL_GRAPHVIZ=false
          - INSTALL_IONCUBE=false
          - INSTALL_MYSQL_CLIENT=true
          - INSTALL_PING=false
          - INSTALL_SSHPASS=false
          - INSTALL_INOTIFY=false
          - INSTALL_FSWATCH=false
          - INSTALL_AST=true
          - INSTALL_YAML=false
          - INSTALL_RDKAFKA=false
          - INSTALL_MAILPARSE=false
          - INSTALL_GIT_PROMPT=false
          - INSTALL_XMLRPC=false
          - PUID=1000
          - PGID=1000
          - CHROME_DRIVER_VERSION=2.42
          - NODE_VERSION=node
          - YARN_VERSION=latest
          - DRUSH_VERSION=8.4.6
          - AST_VERSION=1.0.10
          - IMAGEMAGICK_VERSION=latest
          - TZ=UTC
          - BLACKFIRE_CLIENT_ID=
          - BLACKFIRE_CLIENT_TOKEN=
          - INSTALL_POWERLINE=false
          - INSTALL_SUPERVISOR=false
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_GNU_PARALLEL=false
          - INSTALL_LNAV=false
          - INSTALL_PROTOC=false
          - INSTALL_PHPDECIMAL=false
          - INSTALL_ZOOKEEPER=false
          - PROTOC_VERSION=latest
          - INSTALL_DOCKER_CLIENT=false
          - INSTALL_MEMCACHED=true
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../:/var/www:cached
        - docker-in-docker:/certs/client
        - ./php-worker/supervisord.d:/etc/supervisord.d
      extra_hosts:
        - "dockerhost:10.0.75.1"
      ports:
        - "2222:22"
        # - "3000:3000"
        # - "3001:3001"
        # - "8080:8080"
        # - "8001:8000"
        # - "4200:4200"
      tty: true
      environment:
        - PHP_IDE_CONFIG=serverName=laradock
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
      networks:
        - frontend
        - backend
      links:
        - mariadb

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          - CHANGE_SOURCE=false
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=7.4
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_BZ2=false
          - INSTALL_ENCHANT=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=
          - INSTALL_SSH2=false
          - INSTALL_SOAP=false
          - INSTALL_XSL=false
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_GEARMAN=false
          - INSTALL_MSSQL=false
          - INSTALL_BCMATH=true
          - INSTALL_PHPREDIS=true
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=true
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_MYSQLI=true
          - INSTALL_PGSQL=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_POSTGIS=false
          - INSTALL_INTL=true
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_LDAP=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_IMAGE_OPTIMIZERS=true
          - INSTALL_IMAGEMAGICK=true
          - INSTALL_CALENDAR=false
          - INSTALL_FAKETIME=false
          - INSTALL_IONCUBE=false
          - INSTALL_APCU=false
          - INSTALL_CACHETOOL=false
          - INSTALL_YAML=false
          - INSTALL_RDKAFKA=false
          - INSTALL_GETTEXT=false
          - INSTALL_ADDITIONAL_LOCALES=true
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_PING=false
          - INSTALL_SSHPASS=false
          - INSTALL_MAILPARSE=false
          - INSTALL_PCNTL=false
          - ADDITIONAL_LOCALES=en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_XHPROF=false
          - INSTALL_XMLRPC=false
          - INSTALL_PHPDECIMAL=false
          - INSTALL_ZOOKEEPER=false
          - DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL=false
          - PUID=1000
          - PGID=1000
          - IMAGEMAGICK_VERSION=latest
          - LOCALE=POSIX
          - PHP_FPM_NEW_RELIC=false
          - PHP_FPM_NEW_RELIC_KEY=0000
          - PHP_FPM_NEW_RELIC_APP_NAME=app_name
          - INSTALL_DOCKER_CLIENT=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
        - ../:/var/www:cached
        - docker-in-docker:/certs/client
      ports:
        - "9003:9003"
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:10.0.75.1"
      environment:
        - PHP_IDE_CONFIG=serverName=laradock
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=-0
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - mariadb

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=false
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
#        - ":81"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MariaDB ##############################################
    mariadb:
      build:
        context: ./mariadb
        args:
          - http_proxy
          - https_proxy
          - no_proxy
          - MARIADB_VERSION=latest
      volumes:
#        - /home/bitnami/.laradock/data/mariadb:/var/lib/mysql
# 2021-04-14 Cambiado por sugerencia de https://gist.github.com/ijaureguialzo/bf10504c742b44122ba62bfafe772c1c
        - mariadb_data:/var/lib/mysql
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
# 2021-05-13 PRODUCCION - Deshabilitamos el puerto; debería poderse acceder por la red backend
      # ports:
      #   - "3306:3306"
      environment:
        - TZ=UTC
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - backend

### Adminer ###########################################
    adminer:
      build:
        context: ./adminer
        args:
          - INSTALL_MSSQL=false
      environment:
          - ADMINER_PLUGINS=
          - ADMINER_DESIGN=pepa-linha
          - ADMINER_DEFAULT_SERVER=mariadb
      ports:
        - "8081:8080"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

